### ISSUE TITLE
No data available (distribution aware data) missing link

### ISSUE THREAD

**Issue by KacemKhaled** [mmazeika/model-stealing-defenses#2]
The link to download the distribution aware data is missing 
[https://github.com/mmazeika/model-stealing-defenses/tree/main/batch_training/condor_scripts/data](https://github.com/mmazeika/model-stealing-defenses/tree/main/batch_training/condor_scripts/data)

**Comment by KacemKhaled** [comment]
Data could be generated again using the notebook provided in the repo, but you have to download the imagenet data separetley.

**Comment by mmazeika** [comment]
Hello,

Sorry, I forgot to add the link. The distribution-aware datasets are available here: https://drive.google.com/drive/folders/1uzv_i2v8RedPYh6r06dWYBKFJ94zdxc-?usp=share_link
